### ISSUE TITLE
Should 'Box2D' be add to requirement.txt?

### ISSUE THREAD

**Issue by tanchihpin0517** [PAIA-Playful-AI-Arena/MLGame#1]
"Box2D" is needed for Maze_Car.
I noticed "Box2D-py" is in the requirement.txt of Paia-Desktop, but it may be too old to install.
Just "Box2D" is enough.

**Comment by kylingithub** [comment]
Thanks for your comment.
There is different box2d package for Windows , Linux and MacOS.

For Linux and MacOS
```
box2d-py==2.3.8
```

For Windows 
```
Box2D==2.3.10
```
And the best way to install box2d in Win10 is that download whl file directly and install.
Please refer to  https://www.lfd.uci.edu/~gohlke/pythonlibs/ and download what you need.

Now our project has been independent to games , so it will not inclued box2d in requirements.txt anymore.
Games could choose which library or version they need.
